### PR TITLE
Fix defination of memchr

### PR DESCRIPTION
**Pull request by sayeed99**
memchr() is define in string.h include string.h to fix it.

Signed-off-by: sayeed99 sayeed.afridi2009@gmail.com

### CODE REVIEW

**Comment by DespairFactor** [comment]
How are you running into this error?

**Comment by sayeed99** [comment]
../../../GCC-UBER/libgomp/config/linux/proc.c: In function 'cpuList_parse':
../../../GCC-UBER/libgomp/config/linux/proc.c:172:13: error: implicit declaration of function 'memchr' [-Werror=implicit-function-declaration]
         q = memchr(p, ',', end-p);
             ^
../../../GCC-UBER/libgomp/config/linux/proc.c:172:13: error: incompatible implicit declaration of built-in function 'memchr' [-Werror]
../../../GCC-UBER/libgomp/config/linux/proc.c:172:13: note: include '<string.h>' or provide a declaration of 'memchr'

here is the error log, I was doing a cross compile build for x86_64 architecture with libgomp enabled.

**Comment by DespairFactor** [comment]
Your target is x86_64? or do you mean your x86_64 is your host?

**Comment by sayeed99** [comment]
target is x86_64-linux-android, I am a developer for zenfone 2, and wanted to put up a cross TC for it,

I am building binutils separately 
here is the configure command for it

../binutils/configure --target=x86_64-linux-android --prefix=$PREFIX --host=x86_64-linux-gnu --build=x86_64-linux-gnu --with-gnu-ld --with-gnu-as --with-gold --enable-gold=default --enable-languages=c,c++ --enable-cloog-backend=isl --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --disable-libssp --enable-threads --disable-nls --disable-libmudflap --disable-libgomp --disable-libstdc__-v3 --disable-sjlj-exceptions --disable-shared --disable-tls --disable-libitm --with-arch=x86-64 --with-tune=intel --with-fpmath=sse --with-multilib-list=m32,m64,mx32 --enable-initfini-array --disable-nls --with-sysroot=/home/cyborg/zenfone/newTC/sysroot/arch-x86_64 --with-gxx-include-dir=/home/cyborg/zenfone/newTC/sysroot/arch-x86_64/c++ --with-python --with-bugurl=sayeed.afridi2009@gmail.com --disable-bootstrap --enable-plugins --disable-libcilkrts --disable-libsanitizer --enable-threads --enable-graphite=yes --enable-eh-frame-hdr-for-static --disable-werror --disable-libssp --program-transform-name='s&^&x86_64-linux-android-&'

this goes fine

and I am building mpfr, gdb, mpc and all other dependencies in GCC tree with this config

../GCC-UBER/configure --target=x86_64-linux-android --prefix=$PREFIX --host=x86_64-linux-gnu --build=x86_64-linux-gnu --with-gnu-ld --with-gnu-as --enable-languages=c,c++ --enable-cloog-backend=isl --program-transform-name='s&^&x86_64-linux-android-&' --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --disable-libssp --enable-threads --disable-nls --disable-libmudflap --disable-libstdc__-v3 --disable-sjlj-exceptions --disable-shared --disable-tls --disable-libitm --with-arch=x86-64 --with-tune=intel --with-fpmath=sse --with-multilib-list=m32,m64,mx32 --enable-initfini-array --disable-nls --with-sysroot=/home/cyborg/zenfone/newTC/sysroot/arch-x86_64 --with-gxx-include-dir=/home/cyborg/zenfone/newTC/sysroot/arch-x86_64/c++ --with-python --with-bugurl=sayeed.afridi2009@gmail.com --disable-bootstrap --enable-plugins --enable-libgomp --enable-gnu-indirect-function --disable-libcilkrts --disable-libsanitizer --enable-threads --enable-gold --enable-gold=default --enable-graphite=yes --disable-werror --enable-eh-frame-hdr-for-static

on doing a make -j4 everything goes good, but as soon as you do make install , you will run into that error.  

edit : I export environment
export TARGET=x86_64-linux-android
export PREFIX=/home/cyborg/zenfone/newTC/output/$TARGET
export PATH=$PATH:$PREFIX/bin

**Comment by DespairFactor** [comment]
Message me on hangouts matthewdalex92@gmail.com

**Comment by sayeed99** [comment]
alright, done.

**Pull request closed without merging**
